### PR TITLE
Release/2.1.0

### PR DESCRIPTION
**Pull request by korzio**

### CODE REVIEW

**Comment by Anthropic** [comment]
@korzio does the error message change complete the error compatibility request in #54?

**Comment by korzio** [comment]
@Anthropic Yes, I think it does, thanks! I will do the last checks and close it

**Comment by korzio** [comment]
@Anthropic the field `message` is still missing. I've started template function refactoring before the release and a message implementation should go after. So no, unfortunately there is still some work should be done there.

**Comment by Anthropic** [comment]
@korzio did you see: [this issue](https://github.com/json-schema-org/json-schema-spec/issues/396#issuecomment-398496923) you were tagged in by Henry?

May be worth your time following as it discusses standardizing the error output in draft-08.

**Comment by korzio** [comment]
Thx @Anthropic great that we gonna have a standard error

**Pull request merged**
